" VIM

" Plugins
" =======

call plug#begin()
" Python code formatter
Plug 'python/black'
Plug 'jiangmiao/auto-pairs'
call plug#end()

" General Settings
" ================

syntax on
filetype indent plugin on
set nocompatible    " disable  vi compatibility mode
set history=1000    " increase history size
set encoding=utf-8
set mouse=a
set hidden
set number
set noswapfile      " disable swapfiles
set nobackup        " disable backup files
set termguicolors

"" indent settings
set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4

" Mappings
" ========

" control tabs
map <C-t> :tabnew<cr>
map <C-w> :tabclose<cr>
map <C-left> :tabp<cr>
map <C-right> : tabn<cr>

" open shell
nmap <silent> <C-D> :shell<CR>

" select all
noremap <C-a> ggVG<CR>

" copy to clipboard
noremap <RightMouse> "+y
